# **1. Lowering**

In [15]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [18]:
# Lowecasing in one string
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [19]:
# Lowering on the whole corpus
df['review'] = df['review'].str.lower()

In [20]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# **2. Remove HTML Tags**

To find the HTML Tags in the given string by using the regex we can do that by this pattern matching that is: `<.*?>`

In [21]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [22]:
df['review'] = df['review'].apply(remove_html_tags)

In [23]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# **3. Remove URLs**

In [24]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [25]:
text1 = 'Check out my notebook: https://www.kaggle.com/tmleyncodes/901eu91ji2h982yr892hf2'
text2 = 'Check out my notebook: https://www.kaggle.com/tmleyncodes/9wudghvhv89evfnheq9'
text3 = 'Google Search here: www.google.com'
text4 = 'Check ask: www.chatgpt.com'

In [26]:
print(remove_url(text1))
print(remove_url(text2))
print(remove_url(text3))
print(remove_url(text4))

Check out my notebook:
Check out my notebook:
Google Search here:
Check ask:

# **4. Remove Punctuation**

All the punctuation marks: `'!"#$%&\'()*+,-./:;<=>?@[\\]^{|}~'`

In [27]:
import string,time
exclude = string.punctuation
print(exclude)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [28]:
def remove_punctuations(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [29]:
text = 'string, with, punctuation!'
start = time.time()
print(f"After Removing Punctuations: {remove_punctuations(text)}")
total_time1 = time.time() - start
print(f"The total time taken to run this: {total_time1} ms")

After Removing Punctuations: string with punctuation
The total time taken to run this: 0.0001881122589111328 ms

In [30]:
def remove_Punctuations_optimal(text):
    return text.translate(str.maketrans('','',exclude))

In [31]:
text = 'string, with, punctuation!'
start = time.time()
print(f"After Removing Punctuations: {remove_Punctuations_optimal(text)}")
total_time2 = time.time() - start
print(f"The total time taken to run this: {total_time2} ms")

After Removing Punctuations: string with punctuation
The total time taken to run this: 0.00030612945556640625 ms

In [32]:
total_time1 / total_time2

0.6144859813084113

In [33]:
df1 = pd.read_csv('/kaggle/input/twitter-sentiment-analysis-hatred-speech/train.csv')

In [34]:
df1.sample(5)

          id  label                                              tweet
1824    1825      0  itâs #nationalbestfriendsday!ð­ð«ð¬ ta...
19803  19804      0  #hello #twitterworld , #nice #day to all !   #...
27357  27358      0   @user so done!! flight delayed by nearly 5hrs...
384      385      0  dream palace, can we move in already? #stellar...
22118  22119      0  what is a #detoxdiet?  #altwaystoheal! #health...

In [35]:
df1.shape

(31962, 3)

In [36]:
df1['tweet'] = df1['tweet'].apply(remove_Punctuations_optimal)

In [37]:
df1.sample(5)

          id  label                                              tweet
27204  27205      0  you cant help the damsel if she loves her mise...
219      220      0  good day  6 new beers at bridpo food amp beer ...
27125  27126      0  bummer disappointed i wasnt able to replace my...
25712  25713      0  on my way to neighbourgoods in braamfontein ne...
14336  14337      0   user hrcp said that so far this year 229 wome...

# **5. Chat Word Treatment**

In [38]:
internet_slang = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GN": "Good Night",
    "GMTA": "Great Minds Think Alike",
    "GR8": "Great!",
    "G9": "Genius",
    "IC": "I See",
    "ICQ": "I Seek You (also a chat program)",
    "ILU": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "KISS": "Keep It Simple, Stupid",
    "LDR": "Long Distance Relationship",
    "LMAO": "Laugh My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "L8R": "Later",
    "MTE": "My Thoughts Exactly",
    "M8": "Mate",
    "NRN": "No Reply Necessary",
    "OIC": "Oh I See",
    "PITA": "Pain In The A**",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "QPSA?": "Que Pasa?",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "SK8": "Skate",
    "STATS": "Your sex and age",
    "ASL": "Age, Sex, Location",
    "THX": "Thank You",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "WB": "Welcome Back",
    "WTF": "What The F...",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "W8": "Wait...",
    "7K": "Sick:-D Laugher",
    "TFW": "That feeling when",
    "MFW": "My face when",
    "MRW": "My reaction when",
    "IFYP": "I feel your pain",
    "TNTL": "Trying not to laugh",
    "JK": "Just kidding",
    "IDC": "I don’t care",
    "ILY": "I love you",
    "IMU": "I miss you",
    "ADIH": "Another day in hell",
    "ZZZ": "Sleeping, bored, tired",
    "WYWH": "Wish you were here",
    "TIME": "Tears in my eyes",
    "BAE": "Before anyone else",
    "FIMH": "Forever in my heart",
    "BSAAW": "Big smile and a wink",
    "BWL": "Bursting with laughter",
    "BFF": "Best friends forever",
    "CSL": "Can’t stop laughing"
}

In [39]:
internet_slang

{'AFAIK': 'As Far As I Know',
 'AFK': 'Away From Keyboard',
 'ASAP': 'As Soon As Possible',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'A3': 'Anytime, Anywhere, Anyplace',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRT': 'Be Right There',
 'BTW': 'By The Way',
 'B4': 'Before',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FWIW': "For What It's Worth",
 'FYI': 'For Your Information',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GN': 'Good Night',
 'GMTA': 'Great Minds Think Alike',
 'GR8': 'Great!',
 'G9': 'Genius',
 'IC': 'I See',
 'ICQ': 'I Seek You (also a chat program)',
 'ILU': 'I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'KISS': 'Keep It Simple, Stupid',
 'LDR': 'Long Distance Relationship',
 'LMAO': 'Laugh My A** Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'L8R': 'Later',
 'MTE': 'My Thoughts Exactly',
 'M8': 'Mate',
 'NRN': 'No Reply Necessary',
 'OIC': 'Oh I See',
 'PITA': 'Pain In The A**',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'QPSA?': 'Que Pasa?',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
 'SK8': 'Skate',
 'STATS': 'Your sex and age',
 'ASL': 'Age, Sex, Location',
 'THX': 'Thank You',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'WB': 'Welcome Back',
 'WTF': 'What The F...',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'W8': 'Wait...',
 '7K': 'Sick:-D Laugher',
 'TFW': 'That feeling when',
 'MFW': 'My face when',
 'MRW': 'My reaction when',
 'IFYP': 'I feel your pain',
 'TNTL': 'Trying not to laugh',
 'JK': 'Just kidding',
 'IDC': 'I don’t care',
 'ILY': 'I love you',
 'IMU': 'I miss you',
 'ADIH': 'Another day in hell',
 'ZZZ': 'Sleeping, bored, tired',
 'WYWH': 'Wish you were here',
 'TIME': 'Tears in my eyes',
 'BAE': 'Before anyone else',
 'FIMH': 'Forever in my heart',
 'BSAAW': 'Big smile and a wink',
 'BWL': 'Bursting with laughter',
 'BFF': 'Best friends forever',
 'CSL': 'Can’t stop laughing'}

In [40]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in internet_slang:
            new_text.append(internet_slang[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [41]:
chat_conversion("IMHO he is the best")

'In My Honest/Humble Opinion he is the best'

# **6. Spelling Correction**

In [42]:
from textblob import TextBlob
incorrect_text = 'ceetrain conditionas during seveal gennerattionss aret modifiged in the sume manor'
textblb = TextBlob(incorrect_text)
textblb.correct().string

'certain conditions during several gennerattionss are modified in the some manor'

# **7. Removing Stop Words**

In [43]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [44]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append(' ')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return "".join(x)

In [45]:
remove_stopwords('probably my all-time favorite cartoons, doraemon, shinchan, buru-buri zaemon, action kamen, quantum robot')

'probably all-timefavoritecartoons,doraemon,shinchan,buru-burizaemon,actionkamen,quantumrobot'

# **8. Handling Emojies**

In [46]:
import re
def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "\U00002700-\U000027BF"  # Dingbats
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U00002600-\U000026FF"  # Misc symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U000025A0-\U000025FF"  # Geometric Shapes
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [47]:
remove_emojis("Our team won the match! 🏆⚽🇧🇷")

'Our team won the match! '

# **9. Tokenization**

## Using Split Function

In [48]:
# Word Tokenization
sentence1 = 'I am going to delhi'
sentence1.split()

['I', 'am', 'going', 'to', 'delhi']

In [49]:
# Sentence Tokenization
sentence2 = 'I am at new York. I am gonna attend the New York University'
sentence2.split('.')

['I am at new York', ' I am gonna attend the New York University']

In [50]:
# Problems with split function
sentence3 = 'I am going to delhi!'
sentence4 = 'Where do you think the AI will go in 2030?'
print(sentence3.split())
print(sentence4.split('.'))

['I', 'am', 'going', 'to', 'delhi!']
['Where do you think the AI will go in 2030?']

## Using the Regular Expressions

In [51]:
import re
sentence3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sentence3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [52]:
text = """
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
"""
sentences = re.compile('[.~?]').split(text)
sentences

['\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
 ' Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat',
 '\n']

## Using NLTK (Natural Language Toolkit)

In [53]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [54]:
text = """
 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
"""
sent_tokenize(text)

['\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.']

In [55]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at zuck@meta.ai"
sent7 = "A 5km ride will cost you $100"

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [57]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'zuck',
 '@',
 'meta.ai']

In [58]:
word_tokenize(sent7)

['A', '5km', 'ride', 'will', 'cost', 'you', '$', '100']

## Using Spacy

In [59]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [60]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sentence1)

for token in doc4:
    print(token)

I
am
going
to
delhi

In [61]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
zuck@meta.ai

# **10. Stemming and Lemmatization**

Stemming is the process of reducing inflection in qords to their root forms such as mapping a group of words to the same stem even if the stem itself is not a valid word in the Language

Lemmatization, unlike Stemming, reduces the inflected words properly ensuring that the root word belong to the language. In Lemmatization root word is called Lemma. A lemma is the canonical form, dictionary form, or citation form of a set of words.

In [62]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [63]:
sample = 'walk walks walking walked'
stem_words(sample)

'walk walk walk walk'

In [65]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations = "?;!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)
sentence_words 
print("{0:20}{1:20}".format("Word", "Lemma"))
for word in sentence_words:
    print("{0:20}{1:20}".format(word, wordnet_lemmatizer.lemmatize(word)))

Word                Lemma
He                  He
was                 wa
running             running
and                 and
eating              eating
at                  at
same                same
time                time
He                  He
has                 ha
bad                 bad
habit               habit
of                  of
swimming            swimming
after               after
playing             playing
long                long
hours               hour
in                  in
the                 the
Sun                 Sun